name: CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        env:
          cache-name: maven
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build with Maven
        run: mvn clean package

      - name: Move the built artifact
        if: github.ref == 'refs/heads/main'
        run: mv app/target/*.jar docker/

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        
        with:
          images: |
            ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}/eip-client
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=sha
      -
        name: Build and push
        uses: docker/build-push-action@v2
        env: 
          SERVICE: eip-client
        with:
          context: ./docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}